CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL
);
CREATE TABLE IF NOT EXISTS articles (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  content TEXT NOT NULL,
  date DATE NOT NULL,
  author VARCHAR(255) NOT NULL,
  status VARCHAR(50) NOT NULL,
  coverImage VARCHAR(512),
  tags TEXT,
  summary TEXT
);
CREATE TABLE IF NOT EXISTS sponsors (
  id INT AUTO_INCREMENT PRIMARY KEY,
  imageUrl VARCHAR(512) NOT NULL,
  link VARCHAR(512)
);
CREATE TABLE IF NOT EXISTS films (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  subtitle VARCHAR(255),
  youtube VARCHAR(255),
  director VARCHAR(255),
  year INT,
  description TEXT,
  imageUrl VARCHAR(512)
);